steps:
- label: "Wait for 10 seconds and trigger another pipleline"
  command: "sleep 10"
  key: "waiter"

- label: "Wait for 10 seconds and trigger another pipleline"
  command: "sleep 10"
  key: "helper"

trigger: "skiptest123"
depends_on: "waiter"
